/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import navigateToNetworkAttachmentDefinitionsInjectable from "./navigate-to-network-attachment-definitions.injectable";
import networkAttachmentDefinitionsRouteInjectable from "./network-attachment-definitions-route.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(navigateToNetworkAttachmentDefinitionsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(networkAttachmentDefinitionsRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
