/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import networkAttachmentDefinitionApiInjectable from "./api.injectable";
import networkAttachmentDefinitionsRouteComponentInjectable from "./network-attachment-definitions-route-component.injectable";
import networkAttachmentDefinitionsSidebarItemInjectable from "./network-attachment-definitions-sidebar-item.injectable";
import networkAttachmentDefinitionStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(networkAttachmentDefinitionApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(networkAttachmentDefinitionStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(networkAttachmentDefinitionsRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(networkAttachmentDefinitionsSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
