/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import callSessionControlFunctionsRouteInjectable from "./call-session-control-functions-route.injectable";
import navigateToCallSessionControlFunctionsInjectable from "./navigate-to-call-session-control-functions.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(callSessionControlFunctionsRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToCallSessionControlFunctionsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
