/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerCallSessionControlFunctionsInjectables } from "./call-session-control-functions/register-injectables";
import customResourceDefinitionsRouteInjectable from "./custom-resource-definitions.injectable";
import customResourcesRouteInjectable from "./custom-resources-route.injectable";
import navigateToCustomResourceDefinitionsInjectable from "./navigate-to-custom-resource-definitions.injectable";
import navigateToCustomResourcesInjectable from "./navigate-to-custom-resources.injectable";
import { registerInjectables as registerNetworkAttachmentDefinitionsInjectables } from "./network-attachment-definitions/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(customResourceDefinitionsRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(customResourcesRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToCustomResourceDefinitionsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToCustomResourcesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCallSessionControlFunctionsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNetworkAttachmentDefinitionsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
