/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import callSessionControlFunctionApiInjectable from "./api.injectable";
import callSessionControlFunctionsRouteComponentInjectable from "./call-session-control-functions-route-component.injectable";
import callSessionControlFunctionsSidebarItemInjectable from "./call-session-control-functions-sidebar-item.injectable";
import callSessionControlFunctionStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(callSessionControlFunctionApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(callSessionControlFunctionStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(callSessionControlFunctionsRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(callSessionControlFunctionsSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
