/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerClusterSearchInjectables } from "./cluster-search/register-injectables";
import statusBarCurrentStatusInjectable from "./current-status.injectable";
import setStatusBarStatusInjectable from "./set-status-bar-status.injectable";
import statusBarItemRegistratorInjectable from "./status-bar-item-registrator.injectable";
import statusBarItemsInjectable from "./status-bar-items.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(setStatusBarStatusInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(statusBarCurrentStatusInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(statusBarItemRegistratorInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(statusBarItemsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerClusterSearchInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
